# Generated by Django 5.2 on 2025-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='name',
            new_name='train_name',
        ),
        migrations.AlterField(
            model_name='train',
            name='price',
            field=models.IntegerField(),
        ),
    ]
