# Generated by Django 5.2 on 2025-04-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_name_train_train_name_alter_train_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.CharField(max_length=100),
        ),
    ]
