# Generated by Django 5.2 on 2025-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_train_arrival_time_alter_train_departure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='bus_operator',
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.IntegerField(),
        ),
    ]
